MS_COMMON_LATEST_RG                          = "Vmss-MS-Common-Latest-rg"
LOCATION                                     = "UK South"
MS_COMMON_LATEST_VNET                        = "ms-common-latest-vnet"
SUBNET_NAME                                  = "default"
MS_COMMON_LATEST_SCALESET_NAME               = "vmss-ms-common-latest"
MS_NEW_IMAGE_SCALESET_NAME                   = "vmss-ms-newimage-latest"
