MS_COMMON_LATEST_RG                          = "daniela-saturday-rg"
LOCATION                                     = "UK South"
MS_COMMON_LATEST_VNET                        = "daniela-saturday-vnet"
SUBNET_NAME                                  = "default"
MS_COMMON_LATEST_SCALESET_NAME               = "vmss-daniela-saturday"
